package:
  format-version: "1.0.0"
  name: "net_apps_pic32_bz6"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"
  
  dependencies:
    - name: "net"
      type: "package"
      version: "v3.14.0"
    - name: "core"
      type: "package"
      version: "v3.15.1"
    - name: "csp"
      type: "package"
      version: "v3.22.2"
    - name: "bsp"
      type: "package"
      version: "v3.22.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "wolfMQTT"
      type: "package"
      version: "v1.19.2"
    - name: "usb"
      type: "package"
      version: "v3.16.0"
